Web/FeelingSpa.Web/Controllers/BlogPosts/BlogPostsController.cs
namespace FeelingSpa.Web.Controllers.BlogPosts
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using FeelingSpa.Services.Data.Blogposts;
    using FeelingSpa.Web.ViewModels.BlogPost;
    using FeelingSpa.Web.ViewModels.Category;
    using FeelingSpa.Web.ViewModels.Common;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class BlogPostsController : Controller
    {
        private readonly IBlogPostsService blogPostsService;
        private readonly IWebHostEnvironment environment;

        public BlogPostsController(IBlogPostsService blogPostsService, IWebHostEnvironment environment)
        {
            this.blogPostsService = blogPostsService;
            this.environment = environment;
        }

        public async Task<IActionResult> Index(int? sortId) // blogPostId
        {
            if (sortId != null)
            {
                var blogPost = await this.blogPostsService
                    .GetByIdAsync<BlogPostViewModel>(sortId.Value);
                if (blogPost == null)
                {
                    return this.RedirectToAction("Error404", "Home");
                }
            }

            this.ViewData["CurrentSort"] = sortId;

            var blogPosts = await this.blogPostsService
                .GetAllWithSingleAsync<BlogPostViewModel>(sortId);
            var blogPostsList = blogPosts.ToList();

            var count = this.blogPostsService.GetCount();

            var viewModel = new BlogPostsItemsListViewModel()
            {
                BlogPosts = new ItemsList<BlogPostViewModel>(blogPostsList, count),
            };

            return this.View(viewModel);
        }
    }
}

Web/FeelingSpa.Web/Controllers/Categories/CategoriesController.cs
namespace FeelingSpa.Web.Controllers.Categories
{
    using System;
    using System.Threading.Tasks;

    using FeelingSpa.Services.Data.Categories;
    using FeelingSpa.Web.ViewModels.Categories;
    using FeelingSpa.Web.ViewModels.Category;
    using FeelingSpa.Web.ViewModels.Salons;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly IWebHostEnvironment environment;

        public CategoriesController(ICategoriesService categoriesService, IWebHostEnvironment environment)
        {
            this.categoriesService = categoriesService;
            this.environment = environment;
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 4;
            var viewModel = new CategoriesListViewModel()
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                SalonsCount = this.categoriesService.GetCount(),
                Categories = this.categoriesService.GetAll<CategoryInListViewModel>(id, ItemsPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult SingleCategory(int id)
        {
            var viewModel = this.categoriesService.GetById<CategoryInListViewModel>(id);
            if (viewModel == null)
            {
                return this.RedirectToAction("Error404", "Home");
            }

            return this.View(viewModel);
        }
    }
}

Web/FeelingSpa.Web/Controllers/Salons/SalonsController.cs
namespace FeelingSpa.Web.Controllers.Salons
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using FeelingSpa.Data.Models;
    using FeelingSpa.Services.Data.Categories;
    using FeelingSpa.Services.Data.Cities;
    using FeelingSpa.Services.Data.Salons;
    using FeelingSpa.Services.Data.SalonServices;
    using FeelingSpa.Services.Data.Services;
    using FeelingSpa.Web.ViewModels.Salons;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class SalonsController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly ISalonsService salonsService;
        private readonly IWebHostEnvironment environment;
        private readonly ICitiesService citiesService;
        private readonly IServicesService servicesService;
        private readonly ISalonServicesService salonServicesService;

        public SalonsController(ICategoriesService categoriesService, ISalonsService salonsService, IWebHostEnvironment environment, ICitiesService citiesService, IServicesService servicesService, ISalonServicesService salonServicesService)
        {
            this.categoriesService = categoriesService;
            this.salonsService = salonsService;
            this.environment = environment;
            this.citiesService = citiesService;
            this.servicesService = servicesService;
            this.salonServicesService = salonServicesService;
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 6;
            var viewModel = new SalonsListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                SalonsCount = this.salonsService.GetCount(),
                Salons = this.salonsService.GetAll<SalonInListViewModel>(id, ItemsPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult SingleSalon(string id)
        {
            var viewModel = this.salonsService.GetById<SalonWhitServicesViewModel>(id);
            if (viewModel == null)
            {
               return this.RedirectToAction("Error404", "Home");
            }

            return this.View(viewModel);
        }
    }
}

Web/FeelingSpa.Web/Controllers/Search/SearchController.cs
namespace FeelingSpa.Web.Controllers.Search
{
    using FeelingSpa.Services.Data.Categories;
    using FeelingSpa.Services.Data.Salons;
    using FeelingSpa.Web.ViewModels.Category;
    using FeelingSpa.Web.ViewModels.Salons;
    using FeelingSpa.Web.ViewModels.Search;
    using Microsoft.AspNetCore.Mvc;

    public class SearchController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly ISalonsService salonsService;

        public SearchController(ICategoriesService categoriesService, ISalonsService salonsService)
        {
            this.categoriesService = categoriesService;
            this.salonsService = salonsService;
        }

        public IActionResult Index()
        {
            var viewModel = new SearchCategoriesListViewModel()
            {
                Categories = this.categoriesService.GetAllSearch<CategoryNameIdViewModel>(),
            };
            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult List(SearchListInputModel input)
        {
            var viewModel = new ListViewModel
            {
                Salons = this.salonsService
                    .GetByCategories<SalonInListViewModel>(input.Categories),
            };

            return this.View(viewModel);
        }
    }
}

Web/FeelingSpa.Web/Views/Shared/Error404.cshtml
@using FeelingSpa.Common
@{
    this.ViewData["Title"] = "Error 404";
}

<div class="row ml-5">
    <div class="col-6">
        <div class="row">
            <div class="col-7">
               <img src="https://cdn4.vectorstock.com/i/1000x1000/60/73/page-not-found-error-404-template-vector-14996073.jpg"  class="img-fluid">
            </div>
            <div class="col-5 pt-2">
                <h1 style="color: #BA55D3">Oops!</h1>
                <h2>404</h2>
                <h3>Page Not Found!</h3>
            </div>
        </div>
    </div>
    <div class="col-6">
    </div>
</div>

Web/FeelingSpa.Web/Views/Shared/_Layout.cshtml
@using FeelingSpa.Common
@using Microsoft.CodeAnalysis.CSharp.Syntax
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/date-picker.css" asp-append-version="true" />
    <link href="~/css/responsive.min.css" asp-append-version="true" />
    <link href="~/css/sidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
    <link rel="stylesheet" href="fonts/icomoon/style.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/jquery-ui.css">
    <link rel="stylesheet" href="css/style.css">
    @this.RenderSection("Styles", required: false)
</head>
<body>
    <div class="container">
        <header>

            <nav class="navbar navbar-expand-sm navbar-light  bg-white ">
               

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.IsInRole(GlobalConstants.AdministratorRoleName))
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="All">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Salons" asp-action="All">Salons</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BlogPosts" asp-action="Index">BlogPosts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="DetailsReservation">Reservations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Dashboard" asp-action="Index">Admin</a>
                            </li>
                        </ul>
                    </div>
                }
                else if (User.IsInRole("Manager"))
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="All">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Salons" asp-action="All">Salons</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BlogPosts" asp-action="Index">BlogPosts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="DetailsReservation">Reservations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Manager" asp-controller="Dashboard" asp-action="Index">Manager</a>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="All">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Salons" asp-action="All">Salons</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BlogPosts" asp-action="Index">BlogPosts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="DetailsReservation">Reservations</a>
                            </li>
                        </ul>
                    </div>
                }
            </nav>

    </header>
    </div>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <div class="d-flex quick-info-2">
                            <span class="icon icon-home mr-3"></span>
                            <div class="text">
                                <strong class="d-block heading">Visit our Location</strong>
                                <span class="excerpt">4000 Plovdiv Saedinenie-23</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <div class="d-flex quick-info-2">
                            <span class="icon icon-phone mr-3"></span>
                            <div class="text">
                                <strong class="d-block heading">Call us today</strong>
                                <span class="excerpt"><a href="#">+(359) 888 789011</a></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <div class="d-flex quick-info-2">
                            <span class="icon icon-envelope mr-3"></span>
                            <div class="text">
                                <strong class="d-block heading">Send us a message</strong>
                                <span class="excerpt"><a href="#">info@mysite.com</a></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-3 mb-3 mb-lg-0">
                        <div class="d-flex quick-info-2">
                            <span class="icon icon-clock-o mr-3"></span>
                            <div class="text">
                                <strong class="d-block heading">Opening hours</strong>
                                <span class="excerpt">Mon-Fri 9.00:AM - 8.30PM</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    


    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>

    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/jquery-migrate-3.0.1.min.js"></script>
    <script src="js/jquery-ui.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.stellar.min.js"></script>
    <script src="js/jquery.countdown.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/jquery.animateNumber.min.js"></script>
    <script src="js/jquery.waypoints.min.js"></script>

    <script src="js/bootstrap-datepicker.min.js"></script>
    <script src="js/aos.js"></script>
    <script src="js/rangeslider.min.js"></script>


    <script src="js/typed.js"></script>
    <script>
        var typed = new Typed('.typed-words',
            {
                strings: ["pain", " stress", " fatigue"],
                typeSpeed: 80,
                backSpeed: 80,
                backDelay: 4000,
                startDelay: 1000,
                loop: true,
                showCursor: true
            });
    </script>

    <script src="js/main.js"></script>


    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/FeelingSpa.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only">(current)</span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 4; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>