Web/FeelingSpa.Web/Controllers/Reservations/ReservationsController.cs
namespace FeelingSpa.Web.Controllers.Reservations
{
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using FeelingSpa.Data.Models;
    using FeelingSpa.Services.Data.Reservations;
    using FeelingSpa.Services.Data.Salons;
    using FeelingSpa.Services.Data.SalonServices;
    using FeelingSpa.Services.DateTimeParser;
    using FeelingSpa.Web.ViewModels.Reservations;
    using FeelingSpa.Web.ViewModels.SalonServices;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Primitives;

    [Authorize]
    public class ReservationsController : Controller
    {
        private readonly IReservationsService reservationsService;
        private readonly ISalonServicesService salonServicesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IDateTimeParserService dateTimeParserService;
        private readonly ISalonsService salonsService;

        public ReservationsController(IReservationsService reservationsService, ISalonServicesService salonServicesService, UserManager<ApplicationUser> userManager, IDateTimeParserService dateTimeParserService, ISalonsService salonsService)
        {
            this.reservationsService = reservationsService;
            this.salonServicesService = salonServicesService;
            this.userManager = userManager;
            this.dateTimeParserService = dateTimeParserService;
            this.salonsService = salonsService;
        }

        public async Task<IActionResult> DetailsReservation()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var viewModel = new ReservationsListViewModel
            {
                Reservations =
                    await this.reservationsService.GetReservationsByUserAsync<ReservationViewModel>(userId),
            };
            return this.View(viewModel);
        }

        public async Task<IActionResult> MakeReservation(string salonId, int serviceId)
        {
            var salonService =
                await this.salonServicesService.GetByIdAsync<SalonServicesSimpleViewModel>(salonId, serviceId);

            var viewModel = new ReservationInputModel()
            {
                SalonId = salonId,
                ServiceId = serviceId,
            };

            return this.View(viewModel);
        }

        [HttpPost]

        public async Task<IActionResult> MakeReservation(ReservationInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.MakeReservation), new { input.SalonId, input.ServiceId });
            }

            DateTime dateTime;
            try
            {
                dateTime = this.dateTimeParserService.ConvertStrings(input.Date, input.Time);
            }
            catch (System.Exception)
            {
                return this.RedirectToAction(nameof(this.MakeReservation), new { input.SalonId, input.ServiceId });
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.reservationsService.AddAsync(userId, input.SalonId, input.ServiceId, dateTime);

            return this.RedirectToAction(nameof(this.DetailsReservation));
        }

        [HttpGet]
        public async Task<IActionResult> CancelReservation(string id)
        {
            var viewModel = await this.reservationsService.GetByIdAsync<ReservationViewModel>(id);
            if (viewModel == null)
            {
                return this.RedirectToAction("Error404", "Home");
            }

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteReservation(string id)
        {
            await this.reservationsService.DeleteAsync(id);

            return this.RedirectToAction(nameof(this.DetailsReservation));
        }

        public async Task<IActionResult> RatePastReservation(string id)
        {
            var viewModel = await this.reservationsService.GetByIdAsync<ReservationRatingViewModel>(id);
            if (viewModel == null)
            {
                return this.RedirectToAction("Error404", "Home");
            }

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> RateSalon(ReservationRatingViewModel rating)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.RatePastReservation), new { id = rating.Id });
            }

            if (rating.IsSalonRatedByUser == true)
            {
                return this.RedirectToAction(nameof(this.RatePastReservation), new { id = rating.Id });
            }

            await this.reservationsService.RateReservationAsync(rating.Id);
            await this.salonsService.RateSalonAsync(rating.SalonId, rating.RateValue);

            return this.RedirectToAction("SingleSalon", "Salons", new { id = rating.SalonId });
        }
    }
}

Web/FeelingSpa.Web/Views/Reservations/CancelReservation.cshtml
@model FeelingSpa.Web.ViewModels.Reservations.ReservationViewModel
@{
    this.ViewData["Title"] = "Cancel Reservation";
}
<div class="alert alert-info text-center" role="alert">
    <h1>@this.ViewData["Title"]</h1>
</div>

<h3><strong>Are you sure you want to cancel this reservation?</strong></h3>
<form class="col-6 mt-5">
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Date and Time</label>
        <div class="col-sm-7">
            <div class="form-control">@Model.DateTime</div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Salon</label>
        <div class="col-sm-7">
            <div class="form-control">@Model.SalonName</div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Address</label>
        <div class="col-sm-7">
            <div class="form-control">@Model.SalonCityName, @Model.SalonAddress</div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Service</label>
        <div class="col-sm-7">
            <div class="form-control">@Model.ServiceName</div>
        </div>
    </div>
</form>

<div class="col-6 mt-5 ml-5">
    <div class="row ml-5">
        <form method="post">
            <button type="submit" class="btn btn-outline-success"
                    asp-area="" asp-controller="Reservations" asp-action="DeleteReservation" asp-route-id="@Model.Id">
                Yes, Cancel it!
            </button>
        </form>
        <div class="ml-5">
            <a class="btn btn-danger" asp-area="" asp-controller="Reservations" asp-action="DetailsReservation">No! Go Back</a>
        </div>
    </div>
</div>

Web/FeelingSpa.Web/Views/Reservations/CanselReservation.cshtml
@model FeelingSpa.Web.ViewModels.Reservations.ReservationViewModel
@{
    this.ViewData["Title"] = "Cancel Reservation";
}

<h3><strong>Are you sure you want to cancel this reservation?</strong></h3>
<form class="col-6 mt-5">
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Date and Time</label>
        <div class="col-sm-7">
            <div class="form-control">@Model.DateTime</div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Salon</label>
        <div class="col-sm-7">
            <div class="form-control">@Model.SalonName</div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Address</label>
        <div class="col-sm-7">
            <div class="form-control">@Model.SalonCityName, @Model.SalonAddress</div>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-3 col-form-label">Service</label>
        <div class="col-sm-7">
            <div class="form-control">@Model.ServiceName</div>
        </div>
    </div>
</form>

<div class="col-6 mt-5 ml-5">
    <div class="row ml-5">
        <form method="post">
            <button type="submit" class="btn btn-outline-success"
                    asp-area="" asp-controller="Reservations" asp-action="DeleteReservation" asp-route-id="@Model.Id">
                Yes, Cancel it!
            </button>
        </form>
        <div class="ml-5">
            <a class="btn btn-danger" asp-area="" asp-controller="Reservations" asp-action="DetailsReservation">No! Go Back</a>
        </div>
    </div>
</div>

Web/FeelingSpa.Web/Views/Reservations/Create.cshtml
@model FeelingSpa.Web.ViewModels.Reservations.ReservationInputModel
@{ this.ViewData["Title"] = "Make Reservation"; }
@section Styles {
    <link href="~/css/date-picker.css" rel="stylesheet" asp-append-version="true" />
}

<div class="container-fluid ">
    <div class="row justify-content-center mx-0">
        <div class="col-lg-6">
            <div class="card">
                <form autocomplete="off">
                    <div class="card-header">
                        <div class="mx-0 mb-0 row justify-content-sm-center justify-content-start px-1">
                            <input type="text" id="dp1" class="datepicker" placeholder="&#xf073; Pick Date" style="font-family:Arial, FontAwesome" name="date" readonly />
                        </div>
                    </div>
                    <div class="card-body p-3 p-sm-5">
                        <div class="row text-center mx-0">
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">9:00AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">9:30AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">10:00AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">10:30AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">11:00AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">11:30AM</div>
                            </div>
                        </div>
                        <div class="row text-center mx-0">
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">12:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">12:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">1:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">1:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">2:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">2:30PM</div>
                            </div>
                        </div>
                        <div class="row text-center mx-0">
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">3:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">3:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">4:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">4:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">5:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">5:30PM</div>
                            </div>
                        </div>
                        <div class="row text-center mx-0">
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">6:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">6:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">7:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">7:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">8:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">8:30PM</div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-lg-6">
            <div>
                @await Component.InvokeAsync("SalonServiceDetails", new { Model.SalonId, Model.ServiceId })
            </div>
            <form method="post" enctype="multipart/form-data">
                <input asp-for="@Model.SalonId" value="@Model.SalonId" class="form-control" hidden>
                <input asp-for="@Model.ServiceId" value="@Model.ServiceId" class="form-control" hidden>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Date</label>
                    <div class="col-sm-10">
                        <div id="selectedDate" asp-for="@Model.Date" class="form-control" hidden></div>
                        <input asp-for="@Model.Date" value="" class="form-control" required readonly />
                        <span asp-validation-for="Date" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Time</label>
                    <div class="col-sm-10">
                        <div id="selectedTime" asp-for="@Model.Time" class="form-control" hidden></div>
                        <input asp-for="@Model.Time" value="" class="form-control" required readonly />
                        <span asp-validation-for="Time" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row mt-4">
                    <div class="col-sm-10">
                        <button type="submit" class="button button-large button_1 elements_button my-2"
                                asp-area="" asp-controller="Reservations" asp-action="MakeAppointment">
                            Make Appointment
                        </button>
                    </div>
                </div>
            </form>
            <div class="button button-large button_2 elements_button">
                <a asp-area="" asp-controller="Salons" asp-action="SingleSalon" asp-route-id="@Model.SalonId">
                    <span>Cancel</span><span>Cancel</span>
                </a>
            </div>
            <div asp-validation-summary="All" data-valmsg-summary="true"></div>
        </div>

    </div>
</div>

<!--
<div id="selectedDate"></div>
<div id="selectedTime"></div>
-->

@section Scripts {
    <script src="~/js/bootstrap-datepicker.js" asp-append-version="true"></script>
    <script src="~/js/date-picker.js" asp-append-version="true"></script>
    <script type="text/javascript">$.validator.setDefaults({
            ignore: ""
        })</script>
}

Web/FeelingSpa.Web/Views/Reservations/DetailsReservation.cshtml
@using FeelingSpa.Web.ViewModels.Reservations
@model FeelingSpa.Web.ViewModels.Reservations.ReservationsListViewModel
@{
    this.ViewData["Title"] = "Your Reservations";
}
@if (Model.Reservations.Count() == 0)
{

    <div>
        <div class="alert alert-info text-center" role="alert">
            <h1>@this.ViewData["Title"]</h1>
        </div>

        <div class="p-3 mb-2 bg-dark text-white">
            <h3>Nothing booked yet...</h3>
        </div>

        <ul class="list-group">
            <li class="list-group-item list-group-item-dark"> Make a reservation in 3 easy steps:</li>
            <li class="list-group-item list-group-item-secondary">Find a salon.</li>
            <li class="list-group-item list-group-item-secondary">Choose a beauty service.</li>
            <li class="list-group-item list-group-item-secondary">Pick date and time.</li>

        </ul>
        <div class="about_text_2">
            <p>
                Waiting you back here. :)
            </p>
        </div>
    </div>
    <a class="btn btn-outline-info btn-sm" asp-area="" asp-controller="Salons" asp-action="All">Find Salons</a>

}

@if (Model.Reservations.Count() > 0)
{
    <div class="alert alert-info text-center" role="alert">
        <h1>@this.ViewData["Title"]</h1>
    </div>
    <table class="table table-bordered table-striped">
        <h2>Upcoming (@Model.Reservations.Count())</h2>


        <thead class="thead-light">
            <tr>
                <th scope="col">Date and Time</th>
                <th scope="col">Status <span class="text-info">*</span></th>
                <th scope="col">Salon</th>
                <th scope="col">Address</th>
                <th scope="col">Service</th>
                <th scope="col">Cancel</th>
                <th scope="col">Vote</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var reservation in this.Model.Reservations)
            {

                <tr>
                    <th scope="row">@reservation.DateTime.ToString("f")</th>
                    <td>
                        @if (reservation.Confirmed == true)
                        {
                            <span class="badge badge-success">Confirmed</span>
                        }
                        else if (reservation.Confirmed == false)
                        {
                            <span class="badge badge-danger">Declined</span>
                        }
                        else
                        {
                            <span class="badge badge-secondary">Pending</span>}
                    </td>
                    <td>@reservation.SalonName</td>
                    <td>@reservation.SalonCityName, @reservation.SalonAddress</td>
                    <td>@reservation.ServiceName</td>
                    <td>
                        <a class="btn btn-outline-success btn-sm"
                           asp-area="" asp-controller="Reservations" asp-action="CancelReservation" asp-route-id="@reservation.Id">
                            Cancel
                        </a>
                    </td>
                    <td>
                        <a class="btn btn-outline-success btn-sm"
                           asp-area="" asp-controller="Reservations" asp-action="RatePastReservation" asp-route-id="@reservation.Id">
                            Vote
                        </a>
                    </td>

                </tr>



            }
        </tbody>
    </table>
    <div class="row">
        <div class="col-lg-10 ml-lg-5">
            <div class="about_text_highlight">
                Status
            </div>
            <div class="about_text_2">
                <ol>
                    <li>
                        <span class="badge badge-secondary">Pending</span>
                        - Waiting for the Salon's reply.
                    </li>
                    <li>
                        <span class="badge badge-success">Confirmed</span>
                        - Good! Your appointment is confirmed.
                        They are expecting you on the set date and time.
                    </li>
                    <li>
                        <span class="badge badge-danger">Declined</span>
                        - Sorry, the appointment can't happen on the set date and time.
                        Check your email for rescheduling options from the Salon.
                    </li>
                </ol>
                <ul>

                    <li>
                        <div class="button button-large button_1 elements_button mt-4">

                            <a asp-area="" asp-controller="Salons" asp-action="All">
                                <span>Find Salons</span>
                                <span>Find Salons</span>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
}

<hr class="bg-dark m-4" style="height: 6px;" />

<div>
    @await Component.InvokeAsync("PastReservations")
</div>

Web/FeelingSpa.Web/Views/Reservations/MakeReservation.cshtml
@model FeelingSpa.Web.ViewModels.Reservations.ReservationInputModel
@{ this.ViewData["Title"] = "Make Reservation"; }
@section Styles {
    <link href="~/css/date-picker.css" rel="stylesheet" asp-append-version="true" />
}
<div class="container-fluid ">
    <div class="row justify-content-center mx-0">
        <div class="col-lg-6">
            <div class="card">
                <form autocomplete="off">
                    <div class="card-header">
                        <div class="mx-0 mb-0 row justify-content-sm-center justify-content-start px-1">
                            <input type="text" id="dp1" class="datepicker" placeholder="&#xf073; Pick Date" style="font-family:Arial, FontAwesome" name="date" readonly />
                        </div>
                    </div>
                    <div class="card-body p-2 p-sm-6">
                        <div class="row text-center mx-0">
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">9:00AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">9:30AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-1">
                                <div class="cell py-1">10:00AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-1">
                                <div class="cell py-1">10:30AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-1">
                                <div class="cell py-1">11:00AM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-1">
                                <div class="cell py-1">11:30AM</div>
                            </div>
                        </div>
                        <div class="row text-center mx-0">
                            <div class="col-md-2 col-4 my-1 px-1">
                                <div class="cell py-1">12:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-1">
                                <div class="cell py-1">12:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">1:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">1:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">2:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">2:30PM</div>
                            </div>
                        </div>
                        <div class="row text-center mx-0">
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">3:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">3:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">4:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">4:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">5:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">5:30PM</div>
                            </div>
                        </div>
                        <div class="row text-center mx-0">
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">6:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">6:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">7:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">7:30PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">8:00PM</div>
                            </div>
                            <div class="col-md-2 col-4 my-1 px-2">
                                <div class="cell py-1">8:30PM</div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="col-lg-6">
            <div>
                @await Component.InvokeAsync("SalonServiceDetails", new { Model.SalonId, Model.ServiceId })
            </div>
            <form method="post" enctype="multipart/form-data">
                <input asp-for="@Model.SalonId" value="@Model.SalonId" class="form-control" hidden>
                <input asp-for="@Model.ServiceId" value="@Model.ServiceId" class="form-control" hidden>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Date</label>
                    <div class="col-sm-10">
                        <div id="selectedDate" asp-for="@Model.Date" class="form-control" hidden></div>
                        <input asp-for="@Model.Date" value="" class="form-control" required readonly />
                        <span asp-validation-for="Date" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Time</label>
                    <div class="col-sm-10">
                        <div id="selectedTime" asp-for="@Model.Time" class="form-control" hidden></div>
                        <input asp-for="@Model.Time" value="" class="form-control" required readonly />
                        <span asp-validation-for="Time" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row mt-4">
                    <div class="col-sm-10">
                        <button type="submit" class="button button-large button_1 elements_button my-2"
                                asp-area="" asp-controller="Reservations" asp-action="MakeReservation">
                            Make Reservation
                        </button>
                    </div>
                </div>
            </form>
            <div class="button button-large button_2 elements_button">
                <a asp-area="" asp-controller="Salons" asp-action="SingleSalon" asp-route-id="@Model.SalonId">
                    <span>Cancel</span><span>Cancel</span>
                </a>
            </div>
            <div asp-validation-summary="All" data-valmsg-summary="true"></div>
        </div>

    </div>
</div>

<!--
<div id="selectedDate"></div>
<div id="selectedTime"></div>
-->

@section Scripts {
    <script src="~/js/bootstrap-datepicker.js" asp-append-version="true"></script>
    <script src="~/js/date-picker.js" asp-append-version="true"></script>
    <script type="text/javascript">
        $.validator.setDefaults({
            ignore: ""
        })
    </script>
}