Web/FeelingSpa.Web/Areas/Administration/Controllers/CitiesController.cs
namespace FeelingSpa.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using FeelingSpa.Services.Data.Cities;
    using FeelingSpa.Web.ViewModels.City;
    using Microsoft.AspNetCore.Mvc;

    public class CitiesController : AdministrationController
    {
        private readonly ICitiesService citiesService;

        public CitiesController(ICitiesService citiesService)
        {
            this.citiesService = citiesService;
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCityInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.citiesService.CreateAsync(input);
            return this.Redirect("/");
        }
    }
}

Web/FeelingSpa.Web/Areas/Administration/Controllers/DashboardController.cs
namespace FeelingSpa.Web.Areas.Administration.Controllers
{
    using FeelingSpa.Services.Data;
    using FeelingSpa.Web.ViewModels.Administration.Dashboard;

    using Microsoft.AspNetCore.Mvc;

    public class DashboardController : AdministrationController
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

Web/FeelingSpa.Web/Areas/Manager/Controllers/DashboardController.cs
namespace FeelingSpa.Web.Areas.Manager.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class DashboardController : ManagerBaseController
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

Web/FeelingSpa.Web/Controllers/BlogPosts/BlogPostsController.cs
namespace FeelingSpa.Web.Controllers.BlogPosts
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using FeelingSpa.Services.Data.Blogposts;
    using FeelingSpa.Web.ViewModels.BlogPost;
    using FeelingSpa.Web.ViewModels.Category;
    using FeelingSpa.Web.ViewModels.Common;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class BlogPostsController : Controller
    {
        private readonly IBlogPostsService blogPostsService;
        private readonly IWebHostEnvironment environment;

        public BlogPostsController(IBlogPostsService blogPostsService, IWebHostEnvironment environment)
        {
            this.blogPostsService = blogPostsService;
            this.environment = environment;
        }

        public async Task<IActionResult> Index(int? sortId) // blogPostId
        {
            if (sortId != null)
            {
                var blogPost = await this.blogPostsService
                    .GetByIdAsync<BlogPostViewModel>(sortId.Value);
                if (blogPost == null)
                {
                    return this.RedirectToAction("Error404", "Home");
                }
            }

            this.ViewData["CurrentSort"] = sortId;

            var blogPosts = await this.blogPostsService
                .GetAllWithSingleAsync<BlogPostViewModel>(sortId);
            var blogPostsList = blogPosts.ToList();

            var count = this.blogPostsService.GetCount();

            var viewModel = new BlogPostsItemsListViewModel()
            {
                BlogPosts = new ItemsList<BlogPostViewModel>(blogPostsList, count),
            };

            return this.View(viewModel);
        }
    }
}

Web/FeelingSpa.Web/Controllers/Categories/CategoriesController.cs
namespace FeelingSpa.Web.Controllers.Categories
{
    using System;
    using System.Threading.Tasks;

    using FeelingSpa.Services.Data.Categories;
    using FeelingSpa.Web.ViewModels.Categories;
    using FeelingSpa.Web.ViewModels.Category;
    using FeelingSpa.Web.ViewModels.Salons;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly IWebHostEnvironment environment;

        public CategoriesController(ICategoriesService categoriesService, IWebHostEnvironment environment)
        {
            this.categoriesService = categoriesService;
            this.environment = environment;
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 4;
            var viewModel = new CategoriesListViewModel()
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                SalonsCount = this.categoriesService.GetCount(),
                Categories = this.categoriesService.GetAll<CategoryInListViewModel>(id, ItemsPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult SingleCategory(int id)
        {
            var viewModel = this.categoriesService.GetById<CategoryInListViewModel>(id);
            if (viewModel == null)
            {
                return this.RedirectToAction("Error404", "Home");
            }

            return this.View(viewModel);
        }
    }
}

Web/FeelingSpa.Web/Controllers/Salons/SalonsController.cs
namespace FeelingSpa.Web.Controllers.Salons
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using FeelingSpa.Data.Models;
    using FeelingSpa.Services.Data.Categories;
    using FeelingSpa.Services.Data.Cities;
    using FeelingSpa.Services.Data.Salons;
    using FeelingSpa.Services.Data.SalonServices;
    using FeelingSpa.Services.Data.Services;
    using FeelingSpa.Web.ViewModels.Salons;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class SalonsController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly ISalonsService salonsService;
        private readonly IWebHostEnvironment environment;
        private readonly ICitiesService citiesService;
        private readonly IServicesService servicesService;
        private readonly ISalonServicesService salonServicesService;

        public SalonsController(ICategoriesService categoriesService, ISalonsService salonsService, IWebHostEnvironment environment, ICitiesService citiesService, IServicesService servicesService, ISalonServicesService salonServicesService)
        {
            this.categoriesService = categoriesService;
            this.salonsService = salonsService;
            this.environment = environment;
            this.citiesService = citiesService;
            this.servicesService = servicesService;
            this.salonServicesService = salonServicesService;
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 6;
            var viewModel = new SalonsListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                SalonsCount = this.salonsService.GetCount(),
                Salons = this.salonsService.GetAll<SalonInListViewModel>(id, ItemsPerPage),
            };

            return this.View(viewModel);
        }

        public IActionResult SingleSalon(string id)
        {
            var viewModel = this.salonsService.GetById<SalonWhitServicesViewModel>(id);
            if (viewModel == null)
            {
               return this.RedirectToAction("Error404", "Home");
            }

            return this.View(viewModel);
        }
    }
}

Web/FeelingSpa.Web/Areas/Administration/Views/Dashboard/Index.cshtml
@*@model FeelingSpa.Web.ViewModels.Administration.Dashboard.IndexViewModel
@{
    this.ViewData["Title"] = "Admin dashboard";
}*@

@using FeelingSpa.Common
@{
    this.ViewData["Title"] = "Admin Dashboard";
}

<h3>Welcome to Admin Dashboard!</h3>
<p>Here is a quick navigation:</p>
<div>
    <a asp-area="Administration" asp-controller="Salons" asp-action="All"
       class="list-group-item list-group-item-action bg-light">Salons</a>

    <div class="ml-5 my-2">
        <a class="btn btn-outline-info btn-sm" asp-area="Administration" asp-controller="Salons" asp-action="Create">Create Salon</a>
    </div>
    <div class="ml-5 my-2">
        <a class="btn btn-outline-info btn-sm" asp-area="Administration" asp-controller="Salons" asp-action="All">Salons</a>
    </div>
    
    <a asp-area="Administration" asp-controller="Categories" asp-action="All"
       class="list-group-item list-group-item-action bg-light">Categories</a>

    <dvi class="ml-5 my-2">
        <a class="btn btn-outline-info btn-sm" asp-area="Administration" asp-controller="Categories" asp-action="Create">Create Category</a>
    </dvi>
    <dvi class="ml-5 my-2">
        <a class="btn btn-outline-info btn-sm" asp-area="Administration" asp-controller="Categories" asp-action="All">Categories</a>
    </dvi>
    
    <a asp-area="Administration" asp-controller="Services" asp-action="Create"
       class="list-group-item list-group-item-action bg-light">Services</a>

    <div class="ml-5 my-2">
        <a class="btn btn-outline-info btn-sm" asp-area="Administration" asp-controller="Services" asp-action="Create">Create Service</a>
    </div>
    <a asp-area="Administration" asp-controller="Cities" asp-action="Create"
       class="list-group-item list-group-item-action bg-light">Cities</a>

    <div class="ml-5 my-2">
        <a class="btn btn-outline-info btn-sm" asp-area="Administration" asp-controller="Cities" asp-action="Create">Create City</a>
    </div>
    <a asp-area="Administration" asp-controller="BlogPosts" asp-action="All"
       class="list-group-item list-group-item-action bg-light">Blog Posts</a>

    <div class="ml-5 my-2">
        <a class="btn btn-outline-info btn-sm" asp-area="Administration" asp-controller="BlogPosts" asp-action="All">Blog Posts</a>
    </div>
</div>